//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCRUDImplementationWithJquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AdvertOwner { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public DateTime Date { get; set; }
        public Nullable<int> CarDetID { get; set; }
        public Nullable<int> HomeDetID { get; set; }
        public Nullable<int> WorkDetID { get; set; }
    
        public virtual CarDetails CarDetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual HomeDetails HomeDetails { get; set; }
        public virtual State State { get; set; }
        public virtual WorkDetails WorkDetails { get; set; }
    }
}
