//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCRUDImplementationWithJquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeDetails()
        {
            this.Advert = new HashSet<Advert>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Balcony { get; set; }
        public string HeatingSystem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advert> Advert { get; set; }
    }
}
